### ISSUE TITLE
Corregir clases que hemos realizado incorrectas

### ISSUE THREAD

**Issue by Albametnet** [Adalab/dorcas-s4-interacso#2]
Aunque a simple vista el esquema de clases estaba bastante bien, debemos hacer algunos cambios que nos pueden dar problemas a posterior. Lo he observado al realizar variables y supongo que en funcionalidad también darán problemas. No olvidar.

**Comment by oneeyedman** [comment]
@Albametnet asigna solo a una persona, no a todo el equipo
